# Generated by Django 4.2.9 on 2024-04-18 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("estate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="price",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="house",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="estate.address"
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("House", "House"),
                    ("Apartment", "Apartment"),
                    ("Cottage", "Cottage"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="realtor",
            name="rating",
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
