# Generated by Django 4.2.9 on 2024-04-22 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("estate", "0002_house_price_alter_house_address_alter_house_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="house",
            name="condition",
        ),
        migrations.RemoveField(
            model_name="house",
            name="type",
        ),
    ]
