# Generated by Django 4.2.9 on 2024-04-23 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("estate", "0003_remove_house_condition_remove_house_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="houses",
                to="estate.address",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="houses",
                to="estate.owner",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="realtor",
            field=models.ManyToManyField(
                related_name="houses", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="realtor",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=1, default=0.0, max_digits=2, null=True
            ),
        ),
    ]
